services:
  mysql:
    image: mysql:8.4
    container_name: mysql-base
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newsletter
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"