services:
  mysql:
    image: mysql:8.4
    container_name: meu-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"