spring:
  application:
    name: newsletter

  datasource:
    url: jdbc:mysql://localhost:3306/newsletter?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true

  flyway:
    enabled: true
    encoding: utf-8
    password: root
    user: root
    url: jdbc:mysql://localhost:3306/newsletter?createDatabaseIfNotExist=true&serverTimezone=UTC
    locations:
      - classpath:db/migration
      - classpath:db/testData

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER:teste@gmail.com}
    password: ${EMAIL_PASSWORD:qfjo lnbx iaem }
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: ${PORT:8080}
syonet:
  datetime:
    sendNotification: "0 0 8 * * ?"
springdoc:
  api-docs:
    path: /api-docs