spring:
  application:
    name: newsletter
  datasource:
    url: jdbc:mysql://localhost/newsletter?createDatabaseIfNotExist=true
    username: root
    password: root
    hikari:
      maximum-pool-size: 1
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  flyway:
    enabled: true
    encoding: utf-8
    password: root
    user: root
    url: jdbc:mysql://localhost/newsletter?createDatabaseIfNotExist=true
    locations:
      - classpath:db/migration
      - classpath:db/testData
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
